version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: webrtc-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: web_rtc
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        
    redis:
        image: redis:latest
        container_name: webrtc-redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    mysql_data:
    redis_data:
